#数据源
spring:
  datasource:
    url: jdbc:mysql://47.104.11.160:3306/playground?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 910722mu
    driver-class-name: com.mysql.jdbc.Driver
    # Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: playgroundHikariCP
      max-lifetime: 86430000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  servlet:
    context-path: /playground

mybatis:
  configuration:
    map-underscore-to-camel-case: true