#数据源
spring:
  datasource:
    url: jdbc:mysql://47.104.11.160:3306/playground?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 910722mu
    driver-class-name: com.mysql.jdbc.Driver

server:
  servlet:
    context-path: /playground
